name: dart_mcp_host
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/Dartly/dart_mcp_host.git
homepage: https://github.com/Dartly/dart_mcp_host.git
environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  logging: ^1.3.0
  path: ^1.8.0
  logger: ^2.5.0
  mcp_server: ^0.1.9
  # mcp_client: ^0.1.8
  mcp_client:
    git:
      url: https://github.com/Dartly/mcp_client.git
      ref: main

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
